<?php $new_user = $this->url(array("module" => "locale", "controller" => "translate-keys", "action" => "new"), "default", true); ?>
<div class="page-header">
    <h3>
        Keys that can be used
    </h3>
</div>
<div>
    <?php echo $this->form; ?>

    <a href="<?php echo $new_user; ?>" class="btn btn-info pull-right left-05"> <i class="icon-plus-sign"></i>
        Add new key
    </a>
</div>
<br />
<br />
<?php if (count($this->paginator)){ ?>
    <table cellpadding="0" cellspacing="0" width="100%" class="table table-striped table-hover table-bordered">
        <?php echo $this->partial("partials/table_list_header.phtml", "locale", array("headers" => $this->header)); ?>
        <tbody>
            <?php foreach ($this->paginator as $object){ ?>
                <?php
                $edit_url = $this->url(array("module" => "locale", "controller" => "translate-keys", "action" => "edit", "id" => $object->id, "page" => $this->page), "default", true);
                $delete_url = $this->url(array("module" => "locale", "controller" => "translate-keys", "action" => "delete", "id" => $object->id, "page" => $this->page), "default", true);
                ?>
                <tr>
                    <td><?php echo $object->id; ?></td>
                    <td><?php echo $object->key; ?></td>
                    <td><?php echo $object->description; ?></td>
                    <td>
                        <div class="btn-group">
                            <button type="button" class="btn" onclick="location.href='<?php echo $edit_url ?>'">
                                <span class="glyphicon glyphicon-edit" data-original-title="Edit Informations" onmouseover="$(this).tooltip('show');" rel="tooltip"></span>
                            </button>
                            <button type="button" class="btn" href="#" id="<?php echo $object->id;?>" onclick='bootbox.confirm("Are you sure?<br/><br />", function(result){deleteHref(result, "<?php echo $delete_url;?>")});return	false;' >
                                <span class="glyphicon glyphicon-remove" data-original-title="Delete Data" onmouseover="$(this).tooltip('show');" rel="tooltip"></span>
                            </button>
                        </div>
                    </td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
    <?php echo $this->paginationControl($this->paginator, "Sliding", "/partials/pagination_control.phtml"); ?>
<?php } else{ ?>
    <div class="alert alert-info">
        <h3>Records not found.</h3>
    </div>
<?php } ?>

<script type="text/javascript">
                                /**
                                 * Get one user info and show it in modal box
                                 */
                                function viewAdopter(id) {
                                    jQuery.ajax({
                                        url: "<?php echo $this->url(array("module" => "locale", "controller" => "translate-keys", "action" => "show"), "default", true); ?>",
                                        type: "POST",
                                        data: {
                                            id: id
                                        },
                                        dataType: "json",
                                        success: function(result) {
                                            var html = "<b>Id: </b>" + result.id + "<br/>" +
                                                    "<b>Key: </b>" + result.key + "<br/>" +
                                                    "<b>Description: </b>" + result.description;
                                            bootbox.alert(html);
                                        }
                                    });
                                }
</script>
