<div class="page-header">
	<h3>Special privileges for usersgroup <span class="text-info"><?php echo $this->existing->name;?></span>
		<small>
			<p>Add special privileges over a resource by adding the name of privilege, separated by ; .
			Name of the privilege is the last part of the url, for instance 'users/index/edit' - privilege would be edit.</p>
		</small>
	</h3>
</div>
<?php echo $this->form;?>