<?php  $login = $this->url(array('module' => 'admin', 'controller' => 'auth', 'action' => 'login'), 'default', true); ?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title><?php echo Zend_Registry::get('app_name') ?> Admin Panel</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
        <meta name="description" content="">
        <meta name="author" content="">

        <style>.file-input-wrapper { overflow: hidden; position: relative; cursor: pointer; z-index: 1; }.file-input-wrapper input[type=file], .file-input-wrapper input[type=file]:focus, .file-input-wrapper input[type=file]:hover { position: absolute; top: 0; left: 0; cursor: pointer; opacity: 0; filter: alpha(opacity=0); z-index: 99; outline: 0; }.file-input-name { margin-left: 8px; }</style><link rel="stylesheet" href="assets/js/jquery-ui/css/no-theme/jquery-ui-1.10.3.custom.min.css">

        <!-- Neon Theme Styles & Scripts-->

        <link rel="stylesheet" href="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/jquery-ui/css/no-theme/jquery-ui-1.10.3.custom.min.css'); ?>">
        <link rel="stylesheet" href="<?php echo $this->baseUrl('/custom_theme/neon_theme/css/font-icons/entypo/css/entypo.css'); ?>">
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Noto+Sans:400,700,400italic">
        <link rel="stylesheet" href="<?php echo $this->baseUrl('/custom_theme/neon_theme/css/bootstrap.css'); ?>">
        <link rel="stylesheet" href="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/jvectormap/jquery-jvectormap-1.2.2.css'); ?>">
        <link rel="stylesheet" href="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/rickshaw/rickshaw.min.css'); ?>">
        <link rel="stylesheet" href="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/wysihtml5/bootstrap-wysihtml5.css'); ?>">
        <link rel="stylesheet" href="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/codemirror/lib/codemirror.css'); ?>">
        <link rel="stylesheet" href="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/uikit/css/uikit.min.css'); ?>">
        <link rel="stylesheet" href="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/uikit/addons/css/markdownarea.css'); ?>">
        <link rel="stylesheet" href="<?php echo $this->baseUrl('/custom_theme/neon_theme/css/neon-core.css'); ?>">
        <link rel="stylesheet" href="<?php echo $this->baseUrl('/custom_theme/neon_theme/css/neon-theme.css'); ?>">
        <link rel="stylesheet" href="<?php echo $this->baseUrl('/custom_theme/neon_theme/css/neon-forms.css'); ?>">
        <!--<link rel="stylesheet" href="<?php echo $this->baseUrl('/custom_theme/neon_theme/css/neon-rtl.css'); ?>">-->

        <script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/jquery-1.11.0.min.js'); ?>"></script>
        <!--[if lt IE 9]><script src="assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
                <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
                <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- custom_ Styles & Scripts-->
        <link href="<?php echo $this->baseUrl('/css/admin/datepicker.css'); ?>"	rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->baseUrl('/css/admin/chosen.css'); ?>" rel="stylesheet" type="text/css" />
    </head>



    <body class="page-body login-page login-form-fall" data-url="">

        <!-- This is needed when you send requests via Ajax --><script type="text/javascript">
            var baseurl = '';
        </script>
        <div class="login-container">
            <div class="login-header login-caret">	
                <div class="login-content">		
                    <a href="index.html" class="logo">
                    </a>		
                    <p class="description">Dear user, log in to access the admin area!</p>			
                    <!-- progress bar indicator -->
                    <div class="login-progressbar-indicator">
                        <h3>43%</h3>
                        <span>logging in...</span>
                    </div>
                </div>		
            </div>	
            <div class="login-progressbar">
                <div></div>
            </div>	
            <div class="login-form">		
                <div class="login-content">
                    <div class="form-login-error">
                        <h3>Invalid login</h3>
                        <p>Enter <strong>demo</strong>/<strong>demo</strong> as login and password.</p>
                    </div>
                    
                    <form method="post" role="form" id="form_login2" action="<?php echo $login; ?>">
                        <div class="form-group">
                            <div class="input-group">
                                <div class="input-group-addon">
                                    <i class="entypo-user"></i>
                                </div>
                                <input type="text" class="form-control" name="email" id="email" placeholder="E-mail" autocomplete="off" />
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                <div class="input-group-addon">
                                    <i class="entypo-key"></i>
                                </div>
                                <input type="password" class="form-control" name="password" id="password" placeholder="Password" autocomplete="off" />
                            </div>			
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-block btn-login">
                                <i class="entypo-login"></i>
                                Login In
                            </button>
                        </div>
                    </form>

                    <?php //echo $this->form; ?>

                </div>
            </div>
        </div>

        <!-- Neon Theme Bottom Scripts-->       
        <script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/gsap/main-gsap.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/jquery-ui/js/jquery-ui-1.10.3.minimal.min.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/bootstrap.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/joinable.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/resizeable.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/neon-api.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/jvectormap/jquery-jvectormap-1.2.2.min.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/jvectormap/jquery-jvectormap-europe-merc-en.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/jquery.sparkline.min.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/rickshaw/vendor/d3.v3.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/rickshaw/rickshaw.min.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/raphael-min.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/morris.min.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/toastr.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/wysihtml5/wysihtml5-0.4.0pre.min.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/wysihtml5/bootstrap-wysihtml5.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/ckeditor/ckeditor.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/ckeditor/adapters/jquery.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/uikit/js/uikit.min.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/codemirror/lib/codemirror.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/marked.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/uikit/addons/js/markdownarea.min.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/codemirror/mode/markdown/markdown.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/codemirror/addon/mode/overlay.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/codemirror/mode/xml/xml.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/codemirror/mode/gfm/gfm.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/icheck/icheck.min.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/neon-chat.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/jquery.validate.min.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/neon-login.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/neon-custom.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/neon-demo.js'); ?>"></script>

        <!-- custom_ Bottom Scripts -->
        <script src="<?php echo $this->baseUrl('/js/admin/chosen.jquery.min.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/js/admin/bootstrap-filestyle-0.1.0.min.js'); ?>"></script> <!-- file upload element style  -->
        <script src="<?php echo $this->baseUrl('/js/admin/bootstrap-datepicker.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/js/admin/bootbox.min.js'); ?>"></script> <!-- for popups -->
    </body>
</html>