<div id="contact-wraper">
	<div id="letter">
		<div id="contact-leter-content"><p> 	
			<?php echo $this->translate('contact_page_main', false);?>
		</p></div>
	</div>
	<div id="google-map">
		<div id="googleMap"></div>
		<a  id="a-link" target="_blank" href="<?php echo Zend_Registry::get('big_gmap')?>" ><?php echo $this->translate('contact_show_bigger');?></a>
	</div>
	<div id="marker-map"></div>
	<div</div>
	<div id="paper-contact">
		<div id="contact-title"><p><?php echo $this->translate('contact_title', false)?></p></div>
		<div id="dart"></div>

		<div id="content-wraper">

			<div class="contact-content" data-id="1">
				<div class="iner-title">
					<p><?php echo $this->translate('contact_one', false)?></p>
				</div>
				<div class="back-km"><?php echo $this->translate('contact_one_km', false)?></div>
				<div class="minutes simbol1"></div>
				<a href="<?php echo Zend_Registry::get('bg_kop_gmap')?>" target="_blank"><?php echo $this->translate('contact_show_on_gmap');?></a>
			</div>
			<div class="contact-content" data-id="2">
				<div class="iner-title">
					<p><?php echo $this->translate('contact_two', false)?></p>
				</div>
				<div class="back-km"><?php echo $this->translate('contact_two_km', false)?></div>
				<div class="minutes simbol2 "></div>
				<a href="<?php echo Zend_Registry::get('kop_za_gmap')?>" target="_blank"><?php echo $this->translate('contact_show_on_gmap');?></a>
			</div>
			<div class="contact-content" data-id="3">
				<div class="iner-title">
					<p><?php echo $this->translate('contact_three', false)?></p>
				</div>
				<div class="back-km"><?php echo $this->translate('contact_three_km', false)?></div>
				<div class="minutes simbol3"></div>
				<a href="<?php echo Zend_Registry::get('vb_za_gmap')?>" target="_blank"><?php echo $this->translate('contact_show_on_gmap');?></a>
			</div>
			<div class="contact-content" data-id="4">
				<div class="iner-title">
					<p><?php echo $this->translate('contact_four', false)?></p>
				</div>
				<div class="back-km"><?php echo $this->translate('contact_four_km', false)?></div>
				<div class="minutes simbol4"></div>
				<a href="<?php echo Zend_Registry::get('kr_za_gmap')?>" target="_blank"><?php echo $this->translate('contact_show_on_gmap');?></a>
			</div>
			<div class="contact-content" data-id="5">
				<div class="iner-title">
					<p><?php echo $this->translate('contact_five', false)?></p>
				</div>
				<div class="back-km"><?php echo $this->translate('contact_five_km', false)?></div>
				<div class="minutes simbol5"></div>
				<a href="<?php echo Zend_Registry::get('br_za_gmap')?>" target="_blank"><?php echo $this->translate('contact_show_on_gmap');?></a>
			</div>
			<div class="contact-content" data-id="6">
				<div class="iner-title">
					<p><?php echo $this->translate('contact_six', false)?></p>
				</div>
				<div class="back-km"><?php echo $this->translate('contact_six_km', false)?></div>
				<div class="minutes simbol6"></div>
				<a href="<?php echo Zend_Registry::get('al_za_gmap')?>" target="_blank"><?php echo $this->translate('contact_show_on_gmap');?></a>
			</div>
		</div>
		<div id="contact-trip">
			<div id="TA_selfserveprop415" class="TA_selfserveprop"> <ul id="PvWY0HkHw" class="TA_links iVQ3T6i"> <li id="I9X2uN" class="EUGchsYLA"> <a target="_blank" href="http://www.tripadvisor.rs/"><img src="http://www.tripadvisor.rs/img/cdsi/img2/branding/150_logo-11900-2.png" alt="TripAdvisor"/></a> </li> </ul> </div> <script src="http://www.jscache.com/wejs?wtype=selfserveprop&amp;uniq=415&amp;locationId=7280474&amp;lang=sr&amp;rating=true&amp;nreviews=3&amp;writereviewlink=true&amp;popIdx=true&amp;iswide=false&amp;border=true&amp;display_version=2"></script>			
		</div>
		<div id="contact-facebook">
			<div class="facebook">Facebook</div>
			<div class="fb-like facebook-class" data-width="30px" data-layout="button_count" data-action="like" data-show-faces="false" data-share="true"></div>
		</div>
	</div>
	<div id= "googleli">
		<div class="g-page" data-width="180" data-href="//plus.google.com/u/0/110763289417290509926" data-rel="publisher"></div>
		</div>
	<div id="extended-footer6">
		<h3><?php echo $this->translate('about_tel_our_segments');?></h3>
	<div id="welcome-note2"></div>
</div>
</div>
