	<div id="dobro-nam-dosli-mobile"></div>
	<div id="board-front">
		<div id="dobro-nam-dosli"></div>
		<div id="fork-front">
		<div id="index-page-content"><p><?php echo $this->translate('index_page_main');?></p></div>	
		</div>
		<div id="paprika"></div>
		<div id="paprika-2"></div>
		<div id="pepper-front"></div>
		<div id="pepper-front2"></div>
		<div id="extended-footer">
			<p><?php echo $this->translate('index_tel_footer');?></p>
			<h3><?php echo $this->translate('about_tel_our_segments');?></h3>
			<div id="welcome-note"></div>
		</div>
	</div>