<?php $new_user = $this->url(array("module" => "cms", "controller" => "medias", "action" => "new"), "default", true); ?>
<div class="page-header">
    <h2><?php echo $this->media_library->name;?></h2>
</div>
<div class="separator-media">
    <form action="<?php echo $new_user; ?>" class="dropzone" id="my-awesome-dropzone">
    <input type="hidden" name="library_id" value="<?php echo $this->media_library->id;?>">
        <div class="fallback">
            <input name="file" type="file" multiple />
        </div>
    </form>    
</div>
<div class="separator-media">
    <?php echo $this->form; ?>
    <br/>
    <br/>
</div>
<div class="content-reload" data-reloadUrl="<?php echo $this->url(array("module" => "cms", "controller" => "medias", "action" => "index","library_id"=>$this->media_library->id), "default", true); ?>">
    <?php if (count($this->paginator)): ?>
        <table cellpadding="0" cellspacing="0" width="100%" class="table table-striped table-hover table-bordered">
            <?php echo $this->partial("partials/table_list_header.phtml", "cms", array("headers" => $this->header)); ?>
            <tbody>
                <?php foreach ($this->paginator as $object): ?>
                    <?php
                    $edit_url = $this->url(array("module" => "cms", "controller" => "medias", "action" => "edit", "id" => $object->id, "library_id"=>$this->media_library->id, "page" => $this->page), "default", true);
                    $delete_url = $this->url(array("module" => "cms", "controller" => "medias", "action" => "delete", "id" => $object->id, "page" => $this->page), "default", true);
                    ?>
                    <tr>                        
                        <td><?php echo $object->id; ?></td>
                        <td><?php echo $object->title; ?></td>
                        <?php
                            $file_name = $object->file_name; 
                        ?>                        
                        <td><img src="<?php echo My_Utilities::getFullMediaPathDiffSizes($object,'original').'?'.md5(rand(0,100));?>" width="100px"/></td>
                        <td><?php echo $object->created; ?></td>                    
                        <td> <div class="btn-group">
                                <a class="btn" href="<?php echo $edit_url ?>" >
                                    <i class="glyphicon glyphicon-pencil" data-original-title="Edit Informations" onmouseover="$(this).tooltip('show');" rel="tooltip"></i>
                                </a>                                                    
                                <a class="btn" href="#" id="<?php echo $object->id; ?>"
                                   onclick='bootbox.confirm("Da li ste sigurni?<br/><br />", function(result) {
                                            deleteHref(result, "<?php echo $delete_url; ?>")
                                        });
                                        return  false;' >
                                    <i class="glyphicon glyphicon-trash" data-original-title="Delete Data" onmouseover="$(this).tooltip('show');" rel="tooltip"></i>
                                </a> </div>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <?php echo $this->paginationControl($this->paginator, "Sliding", "/partials/pagination_control.phtml"); ?>
    <?php else: ?>
        <div class="alert alert-info">
            <h3>Nijedan zapis nije nađen.</h3>
        </div>
    <?php endif; ?>
</div>