<div id="footer">
	<div class="footer-wrap">
		<div class="footer-section1">
			<div class="footer-section1-right">
			<p><?php echo $this->translate('fo_fallow');?></p>
			</div>
			<div class="social-network">
				<a href="http://www.tripadvisor.com/Restaurant_Review-g6417666-d7280474-Reviews-Zupska_Avlija-Aleksandrovac_Central_Serbia.html"><div class="social-network1"></div></a>
				<a href="https://plus.google.com/110763289417290509926"><div class="social-network2"></div></a>
				<a href="https://www.facebook.com/ZupskaAvlija"><div class="social-network3"></div></a>
			</div>
			<div class="horisontal-wrape">
			<div class="horisontal-line">
				<div class="logo-footer"></div>
				<div class="zupska-avlija-logo-footer"></div>
				<div class="footer-trip">
					<div id="TA_restaurantWidgetGreen169" class="TA_restaurantWidgetGreen"> <ul id="1oaJ5X" class="TA_links gDqqkRTY"> <li id="lj7HQTdAEeiA" class="nwRc2P"> <a target="_blank" href="http://www.tripadvisor.rs/"><img src="http://www.tripadvisor.rs/img/cdsi/partner/tripadvisor_logo_117x18-24177-2.png" alt="TripAdvisor"/></a> </li> </ul> </div> <script src="http://www.jscache.com/wejs?wtype=restaurantWidgetGreen&amp;uniq=169&amp;locationId=7280474&amp;icon=knifeAndFork&amp;lang=sr&amp;display_version=2"></script>
				</div>
				<div>
				<span class="footer-span1"><?php echo $this->translate('fo_idea');?></span><p><a href="#" class="footer-span2"><?php echo $this->translate('fo_name');?></a></p> 
				<span class="footer-span3"><?php echo $this->translate('fo_copyright');?></span>
				</div>
			</div>
			</div>
			</div>

		<div class="footer-section2">
			<div id="qr-code-text"><p class="minus-margin font26px"><?php echo $this->translate('fo_come_1');?><p class="postion"><?php echo $this->translate('fo_come_2');?><span>!</span></p></p></div>
			<div id="qr-code-srb"> </div>
			<div id="symbol-qr"></div>
			<div id="symbol-text">
				<p><?php echo $this->translate('fo_qrcode_1');?></p>
				<p class="green"><?php echo $this->translate('fo_qrcode_2');?><p>
				<p class="ninethine-px"><?php echo $this->translate('fo_qrcode_3');?></p>
				<div class="location"><span><?php echo $this->translate('fo_qrcode_4');?></span> </div>
			</div>
			<div id="right"></div>
		</div>
		<div class="footer-section3">
			<div class="symbols-top"><p><?php echo $this->translate('fo_segments');?></p></div>
			<div class="symbols-wrap">
				<div class="symbols symbol-1"></div>
				<div class="symbols symbol-2"></div>
				<div class="symbols symbol-3"></div>
				<div class="symbols symbol-4"></div>
				<div class="symbols symbol-5"></div>
				<div class="symbols symbol-6"></div>
				<div class="symbols symbol-7"></div>
				<div class="symbols symbol-8"></div>
				<div class="symbols symbol-9"></div>
				<div class="symbols symbol-10"></div>
				<div class="symbols symbol-11"></div>
				<div class="symbols symbol-12"></div>
			</div>
		</div>
	</div>
</div>
<div id="facebook-footer">
	<div class="facebook1">Facebook</div>
	<div class="fb-like" data-width="30px" data-layout="button_count" data-action="like" data-show-faces="false" data-share="true"></div>
</div>