<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" >
	<meta name="title" content="<?php echo $this->translate('meta_title');?>">
	<meta name="description" content="<?php echo $this->translate('meta_description');?>">
	<meta name="keywords" content="<?php echo $this->translate('meta_keywords');?>">
    <meta property="og:title" content='<?php echo $this->fb_title; ?>'/>
    <meta property="og:type" content="website"/>
    <meta property="og:url" content="<?php echo $this->fb_url; ?>"/>
    <meta property="og:image" content="<?php echo $this->fb_image; ?>"/>
    <meta property="og:description" content='<?php echo $this->fb_description; ?>' />  


    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <meta name="apple-mobile-web-app-title" content="<?php echo $this->translate('meta_title');?>" /> 
    <meta name="apple-mobile-web-app-capable" content="no">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=no"> 

	<?php $locale_css_filename = "/css/".strtolower(Zend_Registry::get('Zend_Locale')).".custom.css";?>
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl($locale_css_filename); ?>" media="screen" />	
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('/js/fancyBox/source/jquery.fancybox.css?v=2.1.5'); ?>" media="screen" />

	<script src="<?php echo $this->baseUrl('js/jquery-1.11.0.min.js'); ?>"></script>
	<script src="<?php echo $this->baseUrl('/js/fancyBox/lib/jquery.mousewheel-3.0.6.pack.js'); ?>"></script>
	<script src="<?php echo $this->baseUrl('/js/fancyBox/source/jquery.fancybox.js?v=2.1.5'); ?>"></script>
	<script src="<?php echo $this->baseUrl('/js/fancyBox/source/helpers/jquery.fancybox-media.js?v=1.0.6'); ?>"></script>
	<script src="<?php echo $this->baseUrl("/js/custom.js"); ?>"></script>
	<script src="<?php echo $this->baseUrl("/js/fbox.js"); ?>"></script>

	

	<script src="https://apis.google.com/js/platform.js" async defer>
	  {lang: 'sr'}
	</script>

	<script src="http://maps.googleapis.com/maps/api/js"></script>

	<script src="<?php echo $this->baseUrl('/js/infobox.js'); ?>"></script>
	<script src="<?php echo $this->baseUrl('/js/socials.js'); ?>"></script>
	<script type="text/javascript">
		jQuery(document).ready(function($) {  
			$(window).load(function(){
	    		$('#preloader').fadeOut('slow',function(){$(this).remove();});
			});
		});	
	</script>


</head>
<body >
	<div id="preloader"></div>
	<script>
	  	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  	})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

		ga('create', 'UA-60941906-1', 'auto');
		ga('send', 'pageview');
	</script>
	<script>
		var autoshow_image = "<?php echo $this->autoshow_image; ?>"
	</script>
    <?php echo $this->render('header.phtml') ?>
    <div id="content" class=" <?php echo Zend_Controller_Front::getInstance()->getRequest()->getActionName(); ?>"><?php echo $this->layout()->content ?></div>
    <?php echo $this->render('footer.phtml') ?>


</body>
</html>