<!-- Neon Theme Bottom Scripts-->

<link rel="stylesheet" href="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/select2/select2-bootstrap.css'); ?>">
<link rel="stylesheet" href="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/select2/select2.css'); ?>">
<link rel="stylesheet" href="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/selectboxit/jquery.selectBoxIt.css'); ?>">
<link rel="stylesheet" href="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/daterangepicker/daterangepicker-bs3.css'); ?>">
<link rel="stylesheet" href="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/icheck/skins/minimal/_all.css'); ?>">
<link rel="stylesheet" href="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/icheck/skins/square/_all.css'); ?>">
<link rel="stylesheet" href="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/icheck/skins/flat/_all.css'); ?>">
<link rel="stylesheet" href="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/icheck/skins/futurico/futurico.css'); ?>">
<link rel="stylesheet" href="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/icheck/skins/polaris/polaris.css'); ?>">

<script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/gsap/main-gsap.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/jquery-ui/js/jquery-ui-1.10.3.minimal.min.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/bootstrap.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/joinable.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/resizeable.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/neon-api.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/jvectormap/jquery-jvectormap-1.2.2.min.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/jvectormap/jquery-jvectormap-europe-merc-en.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/jquery.sparkline.min.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/rickshaw/vendor/d3.v3.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/rickshaw/rickshaw.min.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/raphael-min.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/morris.min.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/toastr.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/wysihtml5/wysihtml5-0.4.0pre.min.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/wysihtml5/bootstrap-wysihtml5.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/ckeditor/ckeditor.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/ckeditor/adapters/jquery.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/uikit/js/uikit.min.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/codemirror/lib/codemirror.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/marked.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/uikit/addons/js/markdownarea.min.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/codemirror/mode/markdown/markdown.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/codemirror/addon/mode/overlay.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/codemirror/mode/xml/xml.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/codemirror/mode/gfm/gfm.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/icheck/icheck.min.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/select2/select2.min.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/bootstrap-tagsinput.min.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/typeahead.min.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/selectboxit/jquery.selectBoxIt.min.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/bootstrap-datepicker.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/bootstrap-timepicker.min.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/bootstrap-colorpicker.min.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/daterangepicker/moment.min.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/daterangepicker/daterangepicker.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/jquery.multi-select.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/neon-chat.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/jquery.validate.min.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/neon-login.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/neon-custom.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/neon-demo.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/bootstrap-switch.min.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/jquery.knob.js'); ?>"></script>

<!-- custom Bottom Scripts -->
<script src="<?php echo $this->baseUrl('/js/admin/chosen.jquery.min.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/js/admin/dropzone/dropzone.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/js/admin/bootstrap-filestyle-0.1.0.min.js'); ?>"></script> <!-- file upload element style  -->
<!--<script src="<?php echo $this->baseUrl('/js/admin/bootstrap-datepicker.js'); ?>"></script>-->
<script src="<?php echo $this->baseUrl('/js/admin/custom.admin.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/js/admin/highcharts/highcharts.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/js/admin/highcharts/exporting.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/js/admin/bootbox.min.js'); ?>"></script> <!-- for popups -->
<script src="<?php echo $this->baseUrl('/js/admin/bootstrap-tagsinput-custom.js'); ?>"></script> 