<!-- Neon Theme Styles & Scripts-->
<link rel="stylesheet" href="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/jquery-ui/css/no-theme/jquery-ui-1.10.3.custom.min.css'); ?>">
<link rel="stylesheet" href="<?php echo $this->baseUrl('/custom_theme/neon_theme/css/font-icons/entypo/css/entypo.css'); ?>">
<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Noto+Sans:400,700,400italic">
<link rel="stylesheet" href="<?php echo $this->baseUrl('/custom_theme/neon_theme/css/bootstrap.css'); ?>">
<link rel="stylesheet" href="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/jvectormap/jquery-jvectormap-1.2.2.css'); ?>">
<link rel="stylesheet" href="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/rickshaw/rickshaw.min.css'); ?>">
<link rel="stylesheet" href="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/wysihtml5/bootstrap-wysihtml5.css'); ?>">
<link rel="stylesheet" href="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/codemirror/lib/codemirror.css'); ?>">
<link rel="stylesheet" href="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/uikit/css/uikit.min.css'); ?>">
<link rel="stylesheet" href="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/uikit/addons/css/markdownarea.css'); ?>">
<link rel="stylesheet" href="<?php echo $this->baseUrl('/custom_theme/neon_theme/css/neon-core.css'); ?>">
<link rel="stylesheet" href="<?php echo $this->baseUrl('/custom_theme/neon_theme/css/neon-theme.css'); ?>">
<link rel="stylesheet" href="<?php echo $this->baseUrl('/custom_theme/neon_theme/css/neon-forms.css'); ?>">
<link rel="stylesheet" href="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/selectboxit/jquery.selectBoxIt.css'); ?>">
<link rel="stylesheet" href="<?php echo $this->baseUrl('/custom_theme/neon_theme/fonts/font-awesome/css/font-awesome.min.css'); ?>">
<link rel="stylesheet" href="<?php echo $this->baseUrl('/custom_theme/css/fullcalendar.print.css'); ?>" rel="stylesheet" type="text/css" />
<link rel="stylesheet" href="<?php echo $this->baseUrl('/custom_theme/css/fullcalendar.css'); ?>"	rel="stylesheet" type="text/css" />

<!--<link rel="stylesheet" href="<?php echo $this->baseUrl('/custom_theme/neon_theme/css/neon-rtl.css'); ?>">-->
<link rel="stylesheet" href="<?php echo $this->baseUrl('/custom_theme/css/bootstrap-multiselect.css'); ?>">
<link rel="stylesheet" href="<?php echo $this->baseUrl('/custom_theme/css/fix.css'); ?>">

<script src="<?php echo $this->baseUrl('/custom_theme/neon_theme/js/jquery-1.11.0.min.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/custom_theme/js/bootstrap-multiselect.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/custom_theme/js/fullcalendar.min.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('/js/admin/jquery-ui.min.js'); ?>"></script>
<!--[if lt IE 9]><script src="assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->

<!-- Custom Styles & Scripts-->
<link href="<?php echo $this->baseUrl('/css/admin/chosen.css'); ?>" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->baseUrl('/js/admin/dropzone/dropzone.css'); ?>" rel="stylesheet" type="text/css" />