<?php $new_user = $this->url(array("module"	 => "locale", "controller" => "countries", "action"	 => "new"), "default", true);?>
<div class="page-header">
	<h3>
		Countries where service is available
	</h3>
</div>
<div>
	<?php echo $this->form;?>

	<a href="<?php echo $new_user;?>" class="btn btn-info pull-right left-05"> <i class="icon-plus-sign"></i>
		Add country
	</a>
</div>
<br />
<br />
<?php if(count($this->paginator)){?>
	<table cellpadding="0" cellspacing="0" width="100%" class="table table-striped table-hover table-bordered">
		<?php echo $this->partial("partials/table_list_header.phtml", "locale", array("headers" => $this->header));?>
		<tbody>
			<?php foreach($this->paginator as $object){?>
				<?php
				$edit_url = $this->url(array("module" => "locale", "controller" => "countries", "action"	 => "edit", "id"		 => $object->id, "page"		 => $this->page), "default", true);
				$delete_url	= $this->url(array("module" => "locale", "controller" => "countries", "action"	 => "delete", "id"		 => $object->id, "page"		 => $this->page), "default", true);
				?>	
				<?php if($object->is_active){?>
				<?php $act_deact = $this->url(array('module' => 'locale', 'controller' => 'countries', 'action' => "deactivate", "id" => $object->id, 'page' => $this->page), "default", true);?>
				<?php }else{?>
				<?php $act_deact = $this->url(array('module' => 'locale', 'controller' => 'countries', 'action' => 'activate', 'id' => $object->id, 'page' => $this->page), "default", true);?>
				<?php }?>
				<tr>
					<td><?php echo $object->id;?></td>
					<td><?php echo $object->name;?></td>
					<td><?php echo $object->country_code;?></td>
					<td><?php echo $object->calling_code;?></td>
					<td><?php echo $object->language;?></td>
					<td><?php echo $object->is_active ? 'Yes' : 'No';?></td>
					<td> <div class="btn-group pull-right btn-group-xs">
							<a class="btn" href="" onclick="viewAdopter(<?php echo $object->id;?>); return false;">
								<span class="glyphicon glyphicon-eye-open" data-original-title="View Details" onmouseover="$(this).tooltip('show');" rel="tooltip"></span>
							</a>
							<a href="<?php echo $act_deact;?>" class="btn"> <i class="icon-retweet" data-original-title="Activate / Deactivate"
								onmouseover="$(this).tooltip('show');" rel="tooltip"></i> </a>
							<a class="btn" href="<?php echo $edit_url?>" >
								<span class="glyphicon glyphicon-edit" data-original-title="Edit Informations" onmouseover="$(this).tooltip('show');" rel="tooltip"></span>
							</a>
							<a class="btn" href="#" id="<?php echo $object->id;?>"
							   onclick='bootbox.confirm("Are you sure?<br/><br />", function(result){deleteHref(result, "<?php echo $delete_url;?>")});return	false;' >
								<span class="glyphicon glyphicon-remove" data-original-title="Delete Data" onmouseover="$(this).tooltip('show');" rel="tooltip"></span>
							</a> </div>
					</td>
				</tr>
			<?php }?>
		</tbody>
	</table>
	<?php echo $this->paginationControl($this->paginator, "Sliding", "/partials/pagination_control.phtml");?>
<?php }else{?>
	<div class="alert alert-info">
		<h3>Records not found.</h3>
	</div>
<?php }?>

<script type="text/javascript">
	/**
	 * Get one user info and show it in modal box
	 */
	function viewAdopter(id){
		jQuery.ajax({
			url: "<?php echo $this->url(array("module"	 => "locale", "controller" => "countries", "action"	 => "show"), "default", true);?>",
			type: "POST",
			data: {
				id: id
			},
			dataType: "json",
			success: function(result){
				var html ="<b>Id: </b>"+result.id+"<br/>"+
					"<b>Country code: </b>"+result.country_code+"<br/>"+
					"<b>Country: </b>"+result.name;
				bootbox.alert(html);
			}
		});
	}
</script>
